language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
services:
  - redis-server
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y redis-server
before_script:
  - npm install -g grunt-cli
