twitter:
  consumerKey: "REPLACE WITH YOUR KEY"
  consumerSecret: "REPLACE WITH YOUR SECRET"
  accessToken: "REPLACE WITH YOUR TOKEN"
  accessTokenSecret: "REPLACE WITH YOUR SECRET"

ui:
  # time between updates, in secs
  updateInterval: 1

  # how many tags to display
  numTags: 10

  # how many domains to display
  numDomains: 10
