twitter:
  consumerKey: "REPLACE WITH YOUR KEY"
  consumerSecret: "REPLACE WITH YOUR SECRET"
  accessToken: "REPLACE WITH YOUR TOKEN"
  accessTokenSecret: "REPLACE WITH YOUR SECRET"

redis:
  # connection settings; use null for the default (127.0.0.1:6379)
  host: null
  port: null
  password: null

  # database to use
  database: 0

  # set to a path+file to connect over a Unix socket
  #   (see https://github.com/mranney/node_redis#unix-domain-socket)
  socket: null

  # connection timeout in secs
  timeout: 30

  # auth password
  password: null

ui:
  # time between updates, in secs
  updateInterval: 1

  # how many of these items to display
  numTags: 10
  numDomains: 10
  numLangs: 20
  numCountries: 20
  numSources: 5
  numUsers: 10
  numUrls: 5
